spring:
  profiles:
    active: local
  application:
    name: chatapp-api
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost/chatapp?serverTimezone=UTC
      username: root
      password: root
    jpa:
      open-in-view: false
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect

server:
  servlet:
    context-path: /api
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}

---
spring:
  profiles: local, alpha
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    jpa:
      generate-ddl: true
      show-sql: true
      properties:
        hibernate:
          format_sql: true
---
spring:
  profiles: beta, real
  jpa:
    generate-ddl: false
    show-sql: false

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus