export default {
  fontFamily: 'Arial, Helvetica, sans-serif',
  normalFontSize: '0.9rem',
  smallFontSize: '0.77rem',
  verySmallFontSize: '0.6rem',
  fontWeight: '400',
  fontStyle: 'normal',
  letterSpacing: '0',
  lineHeight: '1.4',
  color: {
    background: 'rgb(255, 254, 252)',
    font: 'rgba(0, 0, 0, 0.84)',
    messageBox: 'rgb(255, 254, 252)',
    myMessage: 'white',
    yourMessage: 'black',
    myMessageBackground: 'linear-gradient(to bottom, #4ac0fc 0%, #006bff 100%)',
    yourMessageBackground: '#E5E5EA',
    messageDate: '#8b8b90',
    link: 'inherit',
  },
};